### ISSUE TITLE
[문서] 주제 명시 및 SRS 초안 작성

### ISSUE THREAD

**Issue by junhodo** [junhodo/UntactSchool#2]
구분 : SRS
요구 사항 : 
* 선출된 주제에 대하여 세부내용 명시
* 세부내용을 바탕으로 BUC, UC를 추출하여 SRS 초안 작성

**Comment by juegonjue** [comment]
[클린 스터디 v0.1.docx](https://github.com/junhodo/UntactSchool/files/5855509/v0.1.docx)

**Comment by dubu4050** [comment]
[클린 스터디 v0.2.docx](https://github.com/junhodo/UntactSchool/files/5855954/v0.2.docx)
