### ISSUE TITLE
[SRS] 회의 내용 반영 업데이트 

### ISSUE THREAD

**Issue by junhodo** [junhodo/UntactSchool#9]
구분 : SRS
요구 사항 :  
* 21/02/16 회의 내용을 반영한 SRS를 Wiki에 업데이트

**Comment by dubu4050** [comment]
[클린_스터디_v0.4.docx](https://github.com/junhodo/UntactSchool/files/6041410/_._v0.4.docx)

**Comment by dubu4050** [comment]
[클린_스터디_v0.5.docx](https://github.com/junhodo/UntactSchool/files/6041411/_._v0.5.docx)
